name: windows

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Update submodules
      run: git submodule update --init --recursive
    - name: Install xmake
      run: winget install xmake
    - name: Build
      run: xmake -y
